### ISSUE TITLE
Enhancement Idea: Add alert type filtering

### ISSUE THREAD

**Issue by pbryan7** [finity69x2/nws_alerts#52]
In my area (and likely many others) there are 'alerts' that the NWS publishes that aren't really severe weather alerts.   For example right now there are 3 "Hydrologic Outlooks" that have been active for the last few days...   They aren't indicating any urgent severe weather, but probability based river flooding forecasts for the spring.   It would be nice if this integration could give the option to filter out certain alert types or "events" that the user doesn't care about for display/automatons...   It could be a user entered list so each user could ignore different types if they wish.

**Comment by finity69x2** [comment]
You can already do this in HA so I think putting it into the integration would be redundant.

**Comment by pbryan7** [comment]
My my current purpose, I've been able to work around this in HA...  but thought if someone was triggering off the alerts sensor being > 0, then some filtering in the integration could be helpful.

**Comment by finity69x2** [comment]
I'm not sure I have the tech skills to do what you are asking.

And since you can already filter the alerts to trigger on what you want in HA then I really don't see the need for it to be in the integration.

the integration provides the data. It's up to the user to use that data the way they see fit.

Sorry.
