### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by sspaul1976** [finity69x2/nws_alerts#58]
Greetings.  First, want to thank you for developing this.  It has come in very handy for helping us with spring tornado warnings and other weather conditions. 

Would it be possible to add all attributes returning from the API in properties: references?  Some of them are there and know there is some concatenation for display description and spoken description, but would be nice to have them all individually as well to fine tune in automations.

Existing:
- expires
- messageType
- severity
- event (as title)

Not included; request to add:
- sent
- received
- onset
- ends
- status
- category
- certainty
- urgency
- sender
- senderName
- headline
- description
- instruction 
- response

**Comment by finity69x2** [comment]
If I added that info to every alert I think that the returned data would be so heavy as to be unreadable unless there was only one or two alerts.

I don't think I'll add anymore data unless you can give me a valid example of how the additional data would help you automate more than what is already there.

TBH, this isn't meant to be a full replacement for the NWS alerts API but just to give important info to help people get advanced warnings etc, for weather that affects them in the moment.

**Comment by regularguy01** [comment]
> Not included; request to add:
>     * certainty
>     * urgency
>     * headline

I can see these being helpful.  Certainty and urgency would help convey the importance of the Storm headed in and allow for greater filtering out on no so urgent or uncertain items.  Although Severity would and does cover a lot of this.
Headline would be good as it is much more Human readable and usable for TTS.

Also I don't think adding some of these would be to heavy.  The 'other' WeatherAlerts plugin has them all.  
I also ma no Python programmer but was going to try to add these on my Forked version and see if i could get it to work.

**Comment by finity69x2** [comment]
I'm not saying it would necessarily be too much trouble to add them but I just don't think that the function of the integration.

Certainty is already included in the display attribute. So it's available to be used.

I think urgency is just another name for severity. Which is included.

Also, if the alert contains a headline (not all do I guess?) it uses that headline for the spoken description attribute. otherwise it uses the event data. So that data is also already available.

So I think all of the things you mostly want are already available.

"The 'other' WeatherAlerts plugin has them all."

Not trying to be snide but if it has everything you want then feel free to use that one instead. 

I have both configured but I just like mine better. Duh... :)

**Comment by regularguy01** [comment]
> "The 'other' WeatherAlerts plugin has them all."
> 
> Not trying to be snide but if it has everything you want then feel free to use that one instead.
> 
> I have both configured but I just like mine better. Duh... :)

Its only meant as a "it can be done"  Not a poke at your work.   I think what you have here is very good.

Mostly my conversation here is to provide feed back to you as a developer.  User feedback is important.   So many integrations don't get user feedback and the developer goes on doing the thing they think is best.
