### ISSUE TITLE
NWS_Alerts_Package.yaml file

### ISSUE THREAD

**Issue by NRutt2005** [finity69x2/nws_alerts#76]
@finity69x2,

My apologies because I don't know where to really leave a comment and receive the beedback that I am looking for in this custom integration. I am trying to make sense of the nws_alerts_package.yaml file and how to make this work but to beable to edit the automations in the UI instead of in the yaml file. I'm also confused by the lines that say ' initial_state: "on" ' is this just a trigger that is when the entity sensor.nws_alerts changes to the "on" state this automation should run or is the initial_state: on for something else and the trigger is for if the state of the entity changes to anything?

I hope my question make sense. I'm not very good at understanding yaml and all that fun stuff just yet.

Thank you

**Comment by finity69x2** [comment]
It's typically better to get help on implementation of automations in HA via the HA forums instead of opening an issue for something like this as it's not technically an issue.

you should go [here](https://community.home-assistant.io/t/severe-weather-alerts-from-the-us-national-weather-service/71853) and popst the question so that I or others can more effectively help you.
