### ISSUE TITLE
GPS phone location only showing 1 alert

### ISSUE THREAD

**Issue by beyondunreal79** [finity69x2/nws_alerts#79]
I have a Samsung Note 20 ultra. I set up to use phone tracker as my alerts location. It did work once today for a watch. But several hours later when I got home, a warning was sent but the sensor.nws_alerts only shows 1 alert. I then tried using precise location (by using zone number for my current location and the sensor.nws_alerts instantly showed 2 alerts (the watch from earlier and the warning) I deleted that and switch back to gps phone tracker, but it still shows only 1 alert.  Any ways to troubleshoot this?

**Comment by finity69x2** [comment]
I'm not sure.

Since they are using two different methods of determining the location for the alerts it's possible that the GPS location really only had one alert.

you can use the NWS alert API directly in your browser using the GPS location of your device instead of the zone info to see if they match at that point.
