### ISSUE TITLE
Filter Options

### ISSUE THREAD

**Issue by dresslerc** [finity69x2/nws_alerts#98]
I am trying to build something like Teslas Storm Watch.  Your integration gets me really close by if there is any weather alarms, then charge my ESS (battery). 

Problem is, currently I can't filter for specific weather events.  For example "Dense Fog", I don't want to charge my battery for that. 

So in short, would like an option to say I only want this integration to count for specific weather types.

**Comment by finity69x2** [comment]
Of course you can filter and announce on those but you would need to do it in HA with an automation. I'm not going to build the filter functionality into this integration since you can do it in HA itself.

use the attributes of the alerts to decide what you want to trigger on.

see the "packages" folder in this repo for examples of the things you can trigger on and adjust accordingly.

If you have any troubles it's better to post the question in the HA community forum in the thread created for this integration.

https://community.home-assistant.io/t/severe-weather-alerts-from-the-us-national-weather-service/71853
